new_data = [{"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "The Neanderthals were a direct ancestor of modern humans.",
             "correct_answer": "False",
             "incorrect_answers": ["True"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "A person can get sunburned on a cloudy day.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "The Doppler effect applies to light.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "The planet Mars has two moons orbiting it.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
             "correct_answer": "False",
             "incorrect_answers": ["True"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "Shrimp can swim backwards.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "Sugar contains fat.",
             "correct_answer": "False",
             "incorrect_answers": ["True"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "Sound can travel through a vacuum.",
             "correct_answer": "False",
             "incorrect_answers": ["True"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "The most frequent subconscious activity repeated by the human body is blinking.",
             "correct_answer": "False",
             "incorrect_answers": ["True"]},
            {"category": "Science & Nature",
             "type": "boolean",
             "difficulty": "medium",
             "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
             "correct_answer": "True",
             "incorrect_answers": ["False"]}
            ]
